### ISSUE TITLE
Error connecting to the server.

### ISSUE THREAD

**Issue by artheadsgames** [zalevsk1y/news-parser#3]
I'm trying to parse feeds/pages but always getting "Error connecting to the server."
Clean Wordpress 5.3.2 installation + plugin from Wordpress.org

**Comment by zalevsk1y** [comment]
What version of PHP do you have? This plugin requires PHP7.

**Comment by VARJkE** [comment]
Hello, i have this error:

Sorry.Something went wrong.
If you wand to send error report please click "Send Report" button. You will be redirected to error report page.Just paste details in "leave comment" section and click "Submit new issue".Thank you.
Details
Title!
TypeError: Cannot read property 'hasOwnProperty' of null
Message!
TypeError: Cannot read property 'hasOwnProperty' of null at t.value (http://localhost/wp-content/plugins/news-parser/public/js/parser_rss-1.0.1.bundle.js?ver=5.4:38:50633) at t.value (http://localhost/wp-content/plugins/news-parser/public/js/parser_rss-1.0.1.bundle.js?ver=5.4:38:49782) at t.value (http://localhost/wp-content/plugins/news-parser/public/js/parser_rss-1.0.1.bundle.js?ver=5.4:38:49462) at ul (http://localhost/wp-content/plugins/news-parser/public/js/parser_rss-1.0.1.bundle.js?ver=5.4:22:83430) at http://localhost/wp-content/plugins/news-parser/public/js/parser_rss-1.0.1.bundle.js?ver=5.4:22:101375 at t.unstable_runWithPriority (http://localhost/wp-content/plugins/news-parser/public/js/parser_rss-1.0.1.bundle.js?ver=5.4:30:3842) at $o (http://localhost/wp-content/plugins/news-parser/public/js/parser_rss-1.0.1.bundle.js?ver=5.4:22:44978) at ku (http://localhost/wp-content/plugins/news-parser/public/js/parser_rss-1.0.1.bundle.js?ver=5.4:22:97867) at cu (http://localhost/wp-content/plugins/news-parser/public/js/parser_rss-1.0.1.bundle.js?ver=5.4:22:94014) at http://localhost/wp-content/plugins/news-parser/public/js/parser_rss-1.0.1.bundle.js?ver=5.4:22:45268
