### ISSUE TITLE
Plugin don't work

### ISSUE THREAD

**Issue by Grebennik** [zalevsk1y/news-parser#4]
Hi, I installed plugin from Wordpress console and there are empty pages :-(
https://prnt.sc/rjrhd2

**Comment by zalevsk1y** [comment]
Hello, please specify which version of Wordpress you are using. Unfortunately I didn’t test this plugin with latest version of WP. You could install Error log plugin and send me error log. That will help me alot. https://wordpress.org/plugins/error-log-monitor/
Thank you.

**Comment by Grebennik** [comment]
Thanks, I already decide on this problem by investigating your code. Install Redux DevTools at Chrome was helpful. Without it, plugin doesn't display pages content

**Comment by zalevsk1y** [comment]
I didn’t import compose from redux. I’ll fix that thank you.
