### ISSUE TITLE
Error parsing page or add post

### ISSUE THREAD

**Issue by VARJkE** [zalevsk1y/news-parser#5]
If you wand to send error report please click "Send Report" button. You will be redirected to error report page.Just paste details in "leave comment" section and click "Submit new issue".Thank you.
Details
Title!
TypeError: Cannot read property 'hasOwnProperty' of null
Message!
TypeError: Cannot read property 'hasOwnProperty' of null at t.value (http://localhost/wp-content/plugins/news-parser/public/js/parser_rss-1.0.1.bundle.js?ver=5.4:38:50633) at t.value (http://localhost/wp-content/plugins/news-parser/public/js/parser_rss-1.0.1.bundle.js?ver=5.4:38:49782) at t.value (http://localhost/wp-content/plugins/news-parser/public/js/parser_rss-1.0.1.bundle.js?ver=5.4:38:49462) at ul (http://localhost/wp-content/plugins/news-parser/public/js/parser_rss-1.0.1.bundle.js?ver=5.4:22:83430) at http://localhost/wp-content/plugins/news-parser/public/js/parser_rss-1.0.1.bundle.js?ver=5.4:22:101375 at t.unstable_runWithPriority (http://localhost/wp-content/plugins/news-parser/public/js/parser_rss-1.0.1.bundle.js?ver=5.4:30:3842) at $o (http://localhost/wp-content/plugins/news-parser/public/js/parser_rss-1.0.1.bundle.js?ver=5.4:22:44978) at ku (http://localhost/wp-content/plugins/news-parser/public/js/parser_rss-1.0.1.bundle.js?ver=5.4:22:97867) at cu (http://localhost/wp-content/plugins/news-parser/public/js/parser_rss-1.0.1.bundle.js?ver=5.4:22:94014) at http://localhost/wp-content/plugins/news-parser/public/js/parser_rss-1.0.1.bundle.js?ver=5.4:22:45268

**Comment by zalevsk1y** [comment]
Hello, thank you for sending me error report. Please could you give me more info so i could reproduce this error:
1)Where did you download this plugin?
2)What version of PHP do you use?
3)What browser do you use?
4)What actions did you take before the error occurred?

Thanks.

**Comment by zalevsk1y** [comment]
I fixed that bug in version 1.0.2. So please download a new [version](https://downloads.wordpress.org/plugin/news-parser.1.0.2.zip). 
Thank you for a bug report.
